export const menuFood = [
    {
        id: 'specialitati-paste',
        label: 'Specialități de Paște',
        items: [
            {
                id: 'drob-de-miel',
                category: 'Vită & miel',
                name: 'Drob de miel',
                weight: '',
                price: '135 RON/kg',
                description:
                    'Organe de miel (ficat, plămâni, inimă), ouă, ceapă verde, mărar, pătrunjel, usturoi, sare, piper, ulei.',
                image: null,
            }, {
                id: 'drob-de-pui-si-porc',
                category: 'Paște',
                name: 'Drob de pui și porc',
                weight: '',
                price: '80 RON/kg',
                description:
                    'Carne de pui și porc, organe de pui, ouă, ceapă verde, mărar, pătrunjel, usturoi, sare, piper, ulei.',
                image: null,
            }, {
                id: 'oua-rosii',
                category: 'Paște',
                name: 'Ouă roșii',
                weight: '',
                price: '3 RON/Bucata',
                description:
                    '',
                image: null,
            }, {
                id: 'oua-umplute',
                category: 'Paște',
                name: 'Ouă umplute',
                weight: '',
                price: '65 RON/kg',
                description:
                    '',
                image: null,
            }, {
                id: 'umar-de-miel-copt-si-afumat',
                category: 'Paște',
                name: 'Umăr de miel copt și afumat',
                weight: '',
                price: '200 RON/kg',
                description:
                    '',
                image: null,
            },
        ]
    }, {
        id: 'ciorbe-supe',
        label: 'Ciorbe & supe',
        items: [
            {
                id: 'ciorba-pui',
                category: 'Ciorbe',
                name: 'Ciorbă de pui',
                weight: '400 g',
                price: '25 RON',
                description:
                'Carne de pui 60 g, ceapă, morcov, țelină, ardei kapia, borș, pătrunjel, tăiței cu ou, sare, piper.',
                image: null,
            },
            {
                id: 'ciorba-burta',
                category: 'Ciorbe',
                name: 'Ciorbă de burtă',
                weight: '400 g',
                price: '28 RON',
                description:
                'Supă de legume (ceapă, morcov, țelină, ardei kapia), burtă vită 60 g, ou, smântână, oțet, usturoi, sare, piper.',
                image: null,
            },
            {
                id: 'ciorba-vacuta',
                category: 'Ciorbe',
                name: 'Ciorbă de văcuță',
                weight: '400 g',
                price: '26 RON',
                description:
                'Carne de vită 60 g, ceapă, morcov, țelină, ardei kapia, mazăre, cartofi, pastă de tomate, borș, pătrunjel, mărar, leuștean, sare, piper, fasole verde.',
                image: null,
            },
            {
                id: 'ciorba-legume',
                category: 'Ciorbe',
                name: 'Ciorbă de legume',
                weight: '400 g',
                price: '22 RON',
                description:
                'Ceapă, morcov, țelină, ardei kapia, mazăre, fasole verde, cartofi, pastă de tomate, borș, pătrunjel, mărar, leuștean, sare.',
                image: null,
            },
            {
                id: 'ciorba-fasole',
                category: 'Ciorbe',
                name: 'Ciorbă de fasole',
                weight: '400 g',
                price: '25 RON',
                description:
                'Fasole boabe, ceapă, morcov, țelină, ardei kapia, pastă de tomate, borș, cimbru, pătrunjel, mărar, leuștean, sare, piper.',
                image: null,
            },
            {
                id: 'ciorba-perisoare',
                category: 'Ciorbe',
                name: 'Ciorbă de perișoare',
                weight: '400 g',
                price: '25 RON',
                description:
                'Ciorbă de legume (ceapă, morcov, țelină, ardei kapia), perișoare din carne tocată, borș, pătrunjel, mărar, leuștean, sare, piper.',
                image: null,
            },
            {
                id: 'ciorba-radauteana',
                category: 'Ciorbe',
                name: 'Ciorbă rădăuțeană',
                weight: '400 g',
                price: '28 RON',
                description:
                'Supă de legume (ceapă, morcov, țelină, ardei kapia), piept de pui 60 g, ou, smântână, usturoi, oțet, sare, piper.',
                image: null,
            },
        ]
    }, {
        id: 'aperitive',
        label: 'Aperitive',
        items: [
            {
                id: 'crema-branza-ardei-copti',
                category: 'Aperitive',
                name: 'Cremă de brânză cu ardei copți și pâinea casei',
                weight: '200 g / 90 g',
                price: '31 RON',
                description:
                'Ardei kapia, brânză fină sărată, ulei de măsline, pâinea casei.',
                image: null,
            },
            {
                id: 'pate-pui-dulceata-ardei',
                category: 'Aperitive',
                name: 'Pate de pui cu dulceață de ardei iute și pâinea casei',
                weight: '200 g / 90 g',
                price: '29 RON',
                description:
                'Ficat pui, unt, morcov, ceapă roșie, merișoare deshidratate, smântână de gătit, vin roșu, ardei kapia, zahăr, oțet, ardei iute roșu, făină.',
                image: null,
            },
            {
                id: 'salata-vinete-painea-casei',
                category: 'Aperitive',
                name: 'Salată de vinete cu pâinea casei',
                weight: '200 g / 90 g',
                price: '25 RON',
                description: 'Vinete coapte, ceapă, ulei de floarea-soarelui.',
                image: null,
            },
            {
                id: 'hummus-painea-casei',
                category: 'Aperitive',
                name: 'Hummus cu pâinea casei',
                weight: '200 g / 90 g',
                price: '25 RON',
                description:
                'Năut, pastă susan, lămâie, ulei de măsline, făină, usturoi, pătrunjel, busuioc, ulei de floarea-soarelui.',
                image: null,
            },
        ]
    }, {
        id: 'salate-paste',
        label: 'Salate & Paste',
        items: [
            {
                id: 'salata-ton',
                category: 'Salate',
                name: 'Salată cu ton',
                weight: '300 g',
                price: '39 RON',
                description:
                'Salată, roșii, castraveți, ardei kapia, ou, ton, ulei de măsline, porumb, lămâie, măsline, ceapă roșie.',
                image: null,
            },
            {
                id: 'salata-greceasca',
                category: 'Salate',
                name: 'Salată grecească',
                weight: '300 g',
                price: '39 RON',
                description:
                'Ardei kapia, castraveți, roșii, măsline, oregano, ceapă roșie, feta, ulei de măsline.',
                image: null,
            },
            {
                id: 'salata-asortata',
                category: 'Salate',
                name: 'Salată asortată',
                weight: '300 g',
                price: '18 RON',
                description:
                'Roșii, castraveți, ceapă roșie, ulei de floarea-soarelui, mărar.',
                image: null,
            },
            {
                id: 'salata-varza',
                category: 'Salate',
                name: 'Salată de varză',
                weight: '200 g',
                price: '12 RON',
                description: 'Varză, ulei de floarea-soarelui, oțet.',
                image: null,
            },
            {
                id: 'salata-sfecla-hrean',
                category: 'Salate',
                name: 'Salată de sfeclă cu hrean',
                weight: '150 g',
                price: '15 RON',
                description: 'Sfeclă roșie, zahăr, oțet, hrean.',
                image: null,
            },
            {
                id: 'spaghetti-carbonara',
                category: 'Paste',
                name: 'Spaghetti Carbonara',
                weight: '300 g',
                price: '49 RON',
                description:
                'Spaghetti, bacon, gălbenuș ou, parmezan, smântână de gătit.',
                image: null,
            },
        ]
    }, {
        id: 'platouri-calde',
        label: 'Platouri calde',
        items: [
            {
                id: 'platou-drag-5pers',
                category: 'Platouri calde',
                name: 'Platou Drag (5 pers)',
                weight: '2 kg',
                price: '225 RON',
                description:
                'Ceafă de porc, pulpă de pui dezosată, cârnați cu cașcaval, cartofi rumeniți cu mărar și usturoi, murături.',
                image: null,
            },
            {
                id: 'platou-gurmandului',
                category: 'Platouri calde',
                name: 'Platoul Gurmandului (6–8 pers)',
                weight: '3,5 kg',
                price: '410 RON',
                description:
                'Mix de preparate calde (conform meniului: carne, garnituri și sosuri, gramaje afișate în meniu).',
                image: null,
            },
            {
                id: 'platou-pui-5pers',
                category: 'Platouri calde',
                name: 'Platou Pui (5 pers)',
                weight: '1,5 kg',
                price: '195 RON',
                description:
                'Piept de pui la grătar, coaste de pui pane, crispy de pui, cartofi pai, salată de varză, sos roze, maioneză cu usturoi.',
                image: null,
            },
        ]
    }, {
        id: 'preparate-peste',
        label: 'Preparate din pește',
        items: [
            {
                id: 'hamsii-cartofi-mujdei',
                category: 'Pește',
                name: 'Hamsii cu cartofi pai și mujdei',
                weight: '150 g / 150 g / 50 g',
                price: '32 RON',
                description: 'Hamsii prăjite, cartofi pai, mujdei de usturoi.',
                image: null,
            },
            {
                id: 'somon-legume-gratar',
                category: 'Pește',
                name: 'Somon cu legume la grătar',
                weight: '150 g / 150 g',
                price: '79 RON',
                description:
                'Somon la grătar, legume la grătar (mix de legume de sezon).',
                image: null,
            },
            {
                id: 'pastrav-mamaliga-mujdei',
                category: 'Pește',
                name: 'Păstrăv prăjit în mălai / grătar cu mămăligă coaptă și mujdei',
                weight: '200 g / 150 g / 50 g',
                price: '64 RON',
                description:
                'Păstrăv, mălai, făină, usturoi, ulei de floarea-soarelui, mămăligă coaptă.',
                image: null,
            },
        ]
    }, {
        id: 'preparate-pui',
        label: 'Preparate din carne de pui',
        items: [
            {
            id: 'kebab-pui-cartofi-salata',
            category: 'Pui',
            name: 'Kebab de pui cu cartofi pai, sos de maioneză cu usturoi, salată de varză și pâinea casei',
            weight: '150 g / 150 g / 50 g / 80 g / 90 g',
            price: '39 RON',
            description:
                'Carne pui kebab, condimente kebab, cartofi pai, maioneză, usturoi, varză, ulei, oțet, făină.',
            image: null,
            },
            {
            id: 'piept-pui-legume-iaurt',
            category: 'Pui',
            name: 'Piept de pui cu legume la grătar și sos de iaurt',
            weight: '150 g / 150 g / 50 g',
            price: '45 RON',
            description:
                'Piept de pui, usturoi, ulei, cimbru, ceapă roșie, dovlecei, ciuperci, ardei kapia, iaurt grecesc, mentă, ulei de măsline, sare, piper.',
            image: null,
            },
            {
            id: 'pulpe-pui-cartofi-muraturi',
            category: 'Pui',
            name: 'Pulpe de pui la grătar cu cartofi rumeniți la cuptor cu mărar și usturoi, murături',
            weight: '150 g / 200 g / 80 g',
            price: '43 RON',
            description:
                'Pulpă de pui, cartofi, mărar, usturoi, castraveți murați.',
            image: null,
            },
            {
            id: 'pui-copt-lent',
            category: 'Pui',
            name: 'Pui copt lent',
            weight: '500 g / 200 g / 80 g',
            price: '62 RON',
            description:
                'Jumătate de pui gătit lent la cuptor, cartofi rustici cu brânză la putină, salată de varză.',
            image: null,
            },
            {
            id: 'snitel-pui-piure-varza',
            category: 'Pui',
            name: 'Șnițel de pui cu piure de cartofi și salată de varză',
            weight: '200 g / 150 g / 80 g',
            price: '41 RON',
            description:
                'Piept de pui, făină, ou, cartofi, lapte, unt, varză, ulei, oțet.',
            image: null,
            },
            {
            id: 'crispy-pui-cartofi-sos',
            category: 'Pui',
            name: 'Crispy de pui cu cartofi pai și sos roze',
            weight: '150 g / 150 g / 50 g',
            price: '35 RON',
            description: 'Piept de pui, făină, ou, cartofi pai, maioneză, ketchup.',
            image: null,
            }, {
                id: 'coaste-pui-pane-cartofi-usturoi',
                category: 'Pui',
                name: 'Coaste de pui pane cu cartofi pai și sos de maioneză cu usturoi',
                weight: '150 g / 150 g / 50 g',
                price: '36 RON',
                description:
                    'Coaste de pui pane, cartofi pai, maioneză, usturoi.',
                image: null,
            },
        ],
    },
    {
        id: 'preparate-vita-miel',
        label: 'Preparate din vită & miel',
        items: [
            {
            id: 'antricot-vita-barabule',
            category: 'Vită & miel',
            name: 'Antricot de vită, barabule coapte cu sos de verdețuri și brânză la putină',
            weight: '200 g / 200 g / 50 g',
            price: '120 RON',
            description:
                'Antricot vită, unt, rozmarin, cimbru, pătrunjel, mărar, ceapă verde, ulei măsline, sare, piper, brânză de oaie la putină, cartofi.',
            image: null,
            },
            {
            id: 'falcute-vitel-piure',
            category: 'Vită & miel',
            name: 'Fălcuțe de vițel cu piure de cartofi',
            weight: '200 g / 150 g',
            price: '84 RON',
            description:
                'Fălcuțe de vițel Black Angus, rozmarin, cartofi, unt, lapte, vin roșu, anason, portocale.',
            image: null,
            }, {
                id: 'pastrama-miel-cartofi-iaurt',
                category: 'Vită & miel',
                name: 'Pastramă de miel, cartofi rustici, sos de iaurt, salată de ceapă roșie cu pătrunjel',
                weight: '200 g / 200 g / 50 g / 30 g',
                price: '105 RON',
                description:
                    'Pastramă de miel, cartofi, usturoi, mentă, iaurt grecesc, ceapă roșie, mărar, oțet, ulei, pătrunjel.',
                image: null,
            }, 
        ],
    },
    {
        id: 'afumaturi-vita',
        label: 'Afumături vită',
        items: [
            {
                id: 'brisket-argentina',
                category: 'Afumături vită',
                name: 'Brisket Argentina',
                weight: '',
                price: '250 RON/kg',
                description:
                    '',
                image: null,
            }, {
                id: 'short-ribs',
                category: 'Afumături vită',
                name: 'Short Ribs',
                weight: '',
                price: '195 RON/kg',
                description:
                    '',
                image: null,
            }, {
                id: 'pulled-beef',
                category: 'Afumături vită',
                name: 'Pulled Beef',
                weight: '',
                price: '195 RON/kg',
                description:
                    '',
                image: null,
            },
        ]
    },
    {
        id: 'preparate-porc',
        label: 'Preparate din porc',
        items: [
            {
            id: 'mici-cartofi-mustar',
            category: 'Porc',
            name: 'Mici cu cartofi pai și muștar',
            weight: '200 g / 200 g / 50 g / 30 g',
            price: '39 RON',
            description:
                'Carne de porc și vită, cartofi pai, muștar, ulei de floarea-soarelui.',
            image: null,
            },
            {
            id: 'aripioara-porc-piure',
            category: 'Porc',
            name: 'Aripioară de porc gătită lent cu piure de cartofi',
            weight: '350 g / 150 g / 80 g',
            price: '59 RON',
            description:
                'Aripioară de porc, cartofi, unt, gogoșari la oțet, piper, boia, lapte.',
            image: null,
            },
            {
            id: 'carnati-porc-branza-cartofi',
            category: 'Porc',
            name: 'Cârnați de porc cu brânză șvaițer, cartofi prăjiți și sos roze',
            weight: '150 g / 150 g / 50 g',
            price: '45 RON',
            description:
                'Cârnați de porc cu brânză șvaițer, cartofi pai, maioneză, ketchup.',
            image: null,
            },
            {
            id: 'ceafa-porc-barabule-branza',
            category: 'Porc',
            name: 'Ceafă de porc coaptă cu barabule coapte, brânză de oaie la putină, sos de verdețuri și murături',
            weight: '200 g / 200 g / 50 g',
            price: '45 RON',
            description:
                'Ceafă de porc, cartofi, brânză de oaie la putină, pătrunjel, mărar, ceapă verde, ulei de măsline, oregano, castraveți murați.',
            image: null,
            },
            {
            id: 'tochitura-moldoveneasca',
            category: 'Porc',
            name: 'Tochitură moldovenească',
            weight: '250 g / 150 g / 80 g',
            price: '56 RON',
            description:
                'Ceafă porc, gușă porc, cârnați de porc, ou, mămăligă, brânză de oaie la putină, murături, sos de roșii, condimente.',
            image: null,
            },
        ],
    },
    {
        id: 'preparate-vegane',
        label: 'Preparate vegane',
        items: [
            {
            id: 'nuggets-vegan-cartofi-maioneza',
            category: 'Vegane',
            name: 'Nuggets vegan cu cartofi pai și maioneză vegană cu usturoi',
            weight: '150 g / 150 g / 50 g',
            price: '39 RON',
            description:
                'Nuggets vegani din proteine de soia, cartofi pai, maioneză vegană, usturoi.',
            image: null,
            },
            {
            id: 'burger-vegan',
            category: 'Vegane',
            name: 'Burger vegan',
            weight: '380 g / 150 g / 50 g',
            price: '65 RON',
            description:
                'Chiflă vegană, sos barbeque, salată, roșii, castraveți murați, burger vegetal, cașcaval vegetal, maioneză vegetală, ketchup, cartofi pai.',
            image: null,
            },
            {
            id: 'salata-greceasca-branza-vegana',
            category: 'Vegane',
            name: 'Salată grecească cu brânză vegană',
            weight: '300 g',
            price: '42 RON',
            description:
                'Roșii, castraveți, ardei kapia, măsline, oregano, brânză vegană din lapte de cocos, ulei de măsline, mix salată, ceapă roșie.',
            image: null,
            },
        ],
    },
    {
        id: 'burgeri',
        label: 'Burgeri',
        items: [
            {
            id: 'gourmand-burger',
            category: 'Burgeri',
            name: 'Gourmand Burger',
            weight: '450 g / 150 g / 50 g',
            price: '65 RON',
            description:
                'Chiflă burger artizanală, carne vită, sos bbq, salată, roșie, castravete murat, dulceață de ardei iute, brânză brie, bacon, dulceață de ceapă, ceapă crocantă, sos roze, cartofi pai.',
            image: null,
            },
            {
            id: 'classic-burger',
            category: 'Burgeri',
            name: 'Classic Burger',
            weight: '400 g / 150 g / 50 g',
            price: '57 RON',
            description:
                'Chiflă burger artizanală, carne vită, sos bbq, salată, roșie, castravete murat, sos cheddar, sos roze, cartofi pai.',
            image: null,
            },
            {
            id: 'cheeseburger',
            category: 'Burgeri',
            name: 'Cheeseburger',
            weight: '350 g / 150 g / 50 g',
            price: '50 RON',
            description:
                'Chiflă burger artizanală, carne vită, sos bbq, sos cheddar, sos roze, cartofi pai.',
            image: null,
            },
        ],
    },
    {
        id: 'pizza',
        label: 'Pizza',
        items: [
                {
                    id: 'pizza-margherita',
                    category: 'Pizza',
                    name: 'Pizza Margherita',
                    weight: '450 g',
                    price: '37 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, busuioc, ulei de măsline, oregano.',
                    image: null,
                },
                {
                    id: 'pizza-salami',
                    category: 'Pizza',
                    name: 'Pizza Salami',
                    weight: '490 g',
                    price: '47 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, salam Milano.',
                    image: null,
                },
                {
                    id: 'pizza-diavola',
                    category: 'Pizza',
                    name: 'Pizza Diavola',
                    weight: '500 g',
                    price: '49 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, salam picant Ventricina, ulei de măsline, ardei iute.',
                    image: null,
                },
                {
                    id: 'pizza-italia',
                    category: 'Pizza',
                    name: 'Pizza Italia',
                    weight: '580 g',
                    price: '64 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, prosciutto crudo, roșii cherry, parmezan.',
                    image: null,
                },
                {
                    id: 'pizza-quattro-formaggi',
                    category: 'Pizza',
                    name: 'Pizza Quattro Formaggi',
                    weight: '450 g',
                    price: '55 RON',
                    description:
                    'Blat pizza, mozzarella fior di latte, brânză Brie, blue cheese, parmezan, ulei de măsline.',
                    image: null,
                },
                {
                    id: 'pizza-quattro-stagioni',
                    category: 'Pizza',
                    name: 'Pizza Quattro Stagioni',
                    weight: '650 g',
                    price: '52 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, prosciutto crudo, măsline Kalamata, ciuperci, anghinare marinată, ulei de măsline.',
                    image: null,
                },
                {
                    id: 'pizza-vegetariana',
                    category: 'Pizza',
                    name: 'Pizza Vegetariana',
                    weight: '520 g',
                    price: '47 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, ardei copți, ceapă roșie, pătrunjel, măsline, porumb, fulgi de drojdie inactivă, mix de salată.',
                    image: null,
                },
                {
                    id: 'pizza-tonno',
                    category: 'Pizza',
                    name: 'Pizza Tonno',
                    weight: '580 g',
                    price: '55 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, ton în ulei, ceapă roșie, măsline Kalamata, lămâie.',
                    image: null,
                },
                {
                    id: 'pizza-gourmand',
                    category: 'Pizza',
                    name: 'Pizza Gourmand',
                    weight: '620 g',
                    price: '65 RON',
                    description:
                    'Blat pizza, mozzarella fior di latte, carne burger vită, ceapă crocantă, dulceață de ardei iute, usturoi, pătrunjel, brânză Brie.',
                    image: null,
                },
                {
                    id: 'pizza-orientala',
                    category: 'Pizza',
                    name: 'Pizza Orientală',
                    weight: '650 g',
                    price: '64 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, cartofi pai, carne de pui kebab, sos de maioneză cu usturoi, ceapă roșie, ulei de măsline, pătrunjel, oțet.',
                    image: null,
                },
                {
                    id: 'pizza-rustica',
                    category: 'Pizza',
                    name: 'Pizza Rustica',
                    weight: '620 g',
                    price: '56 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, bacon, cârnați, ardei kapia, ceapă roșie.',
                    image: null,
                },
                {
                    id: 'pizza-pollo',
                    category: 'Pizza',
                    name: 'Pizza Pollo',
                    weight: '620 g',
                    price: '48 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, piept de pui, porumb, ciuperci, roșii cherry, ulei de măsline.',
                    image: null,
                },
                {
                    id: 'pizza-drag',
                    category: 'Pizza',
                    name: 'Pizza Drag',
                    weight: '650 g',
                    price: '61 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, kaizer afumat, măsline, ouă, brânză de oaie la putină, ceapă verde.',
                    image: null,
                },
                {
                    id: 'pizza-mortadella',
                    category: 'Pizza',
                    name: 'Pizza Mortadella',
                    weight: '620 g',
                    price: '55 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, mortadella, pesto de busuioc, roșii cherry, ricotta.',
                    image: null,
                },
                {
                    id: 'pizza-carnivore',
                    category: 'Pizza',
                    name: 'Pizza Carnivore',
                    weight: '550 g',
                    price: '54 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, cârnați, prosciutto cotto, bacon, salam Milano.',
                    image: null,
                },
                {
                    id: 'pizza-hawaii',
                    category: 'Pizza',
                    name: 'Pizza Hawaii',
                    weight: '620 g',
                    price: '47 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, prosciutto cotto, ananas, oregano.',
                    image: null,
                },
                {
                    id: 'pizza-prosciutto-funghi',
                    category: 'Pizza',
                    name: 'Pizza Prosciutto e Funghi',
                    weight: '580 g',
                    price: '51 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, prosciutto cotto, ciuperci.',
                    image: null,
                },
                {
                    id: 'pizza-carbonara',
                    category: 'Pizza',
                    name: 'Pizza Carbonara',
                    weight: '580 g',
                    price: '51 RON',
                    description:
                    'Blat pizza, mozzarella fior di latte, smântână de gătit, parmezan, ou, bacon, usturoi.',
                    image: null,
                },
                {
                    id: 'pizza-funghi',
                    category: 'Pizza',
                    name: 'Pizza Funghi',
                    weight: '560 g',
                    price: '47 RON',
                    description:
                    'Blat pizza, sos de roșii, mozzarella fior di latte, ciuperci, măsline.',
                    image: null,
                },
                ]

    },
    {
        id: 'garnituri',
        label: 'Garnituri',
        items: [
            {
            id: 'piure-cartofi',
            category: 'Garnituri',
            name: 'Piure cartofi',
            weight: '200 g',
            price: '18 RON',
            description: 'Cartofi, unt, lapte, sare.',
            image: null,
            },
            {
            id: 'cartofi-pai',
            category: 'Garnituri',
            name: 'Cartofi pai',
            weight: '150 g',
            price: '15 RON',
            description: 'Cartofi prăjiți în ulei.',
            image: null,
            },
            {
            id: 'cartofi-rustici-branza',
            category: 'Garnituri',
            name: 'Cartofi rustici cu brânză la putină, usturoi și pătrunjel',
            weight: '200 g',
            price: '25 RON',
            description:
                'Cartofi copți, brânză la putină, usturoi, pătrunjel.',
            image: null,
            },
            {
            id: 'cartofi-pai-parmezan',
            category: 'Garnituri',
            name: 'Cartofi pai cu parmezan și ulei aromatizat',
            weight: '150 g',
            price: '20 RON',
            description:
                'Cartofi, parmezan, sare, ulei de floarea-soarelui, pătrunjel, busuioc, usturoi.',
            image: null,
            },
            {
            id: 'barabule-coapte-branza-verdeturi',
            category: 'Garnituri',
            name: 'Barabule coapte cu brânză la putină și ulei aromatizat cu verdețuri',
            weight: '250 g',
            price: '25 RON',
            description:
                'Cartofi, brânză la putină, ulei de floarea-soarelui, pătrunjel, busuioc, usturoi.',
            image: null,
            },
            {
            id: 'legume-gratar',
            category: 'Garnituri',
            name: 'Legume la grătar',
            weight: '150 g',
            price: '25 RON',
            description:
                'Ceapă roșie, ardei kapia, dovlecei, ciuperci, oregano, usturoi, ulei de măsline.',
            image: null,
            },
        ],
    },
    {
        id: 'sosuri-extra',
        label: 'Sosuri & Extra',
        items: [
            {
            id: 'sos-verdeturi',
            category: 'Sosuri',
            name: 'Sos verdețuri',
            weight: '50 g',
            price: '8 RON',
            description:
                'Pătrunjel, mărar, ceapă verde, ulei de măsline, oregano, chilli, lămâie.',
            image: null,
            },
            {
            id: 'sos-iaurt',
            category: 'Sosuri',
            name: 'Sos de iaurt',
            weight: '50 g',
            price: '8 RON',
            description:
                'Iaurt grecesc, maioneză, usturoi, mentă, lămâie, ulei de măsline.',
            image: null,
            },
            {
            id: 'sos-roze',
            category: 'Sosuri',
            name: 'Sos Roze',
            weight: '50 g',
            price: '8 RON',
            description: 'Maioneză, ketchup.',
            image: null,
            },
            {
            id: 'dulceata-ardei-iute',
            category: 'Sosuri',
            name: 'Dulceață de ardei iute',
            weight: '50 g',
            price: '8 RON',
            description: 'Ardei kapia, ardei iute, oțet, zahăr.',
            image: null,
            },
            {
            id: 'painea-casei-extra',
            category: 'Extra',
            name: 'Pâinea casei',
            weight: null,
            price: '5 RON',
            description: 'Pâine de casă.',
            image: null,
            },
            {
            id: 'focaccia-simpla',
            category: 'Extra',
            name: 'Focaccia',
            weight: '270 g',
            price: '10 RON',
            description: 'Blat pizza, ulei de măsline, oregano.',
            image: null,
            },
            {
            id: 'focaccia-usturoi-rozmarin',
            category: 'Extra',
            name: 'Focaccia cu usturoi și rozmarin',
            weight: '280 g',
            price: '15 RON',
            description: 'Blat pizza, parmezan, rozmarin, usturoi.',
            image: null,
            },
            {
            id: 'focaccia-mozzarella',
            category: 'Extra',
            name: 'Focaccia cu mozzarella',
            weight: '320 g',
            price: '15 RON',
            description: 'Blat pizza, mozzarella fior di latte.',
            image: null,
            },
        ],
    },
    {
        id: 'desert',
        label: 'Desert',
        items: [
            {
            id: 'clatite-ciocolata-inghetata',
            category: 'Desert',
            name: 'Clătite cu ciocolată și înghețată',
            weight: '150 g',
            price: '27 RON',
            description:
                'Ou, făină, zahăr, lapte, cremă Finetti, înghețată.',
            image: null,
            },
            {
            id: 'inghetata-asortata',
            category: 'Desert',
            name: 'Înghețată asortată',
            weight: '150 g',
            price: '25 RON',
            description: 'Înghețată de vanilie, ciocolată, fructe de pădure.',
            image: null,
            },
            {
            id: 'papanasi-afine',
            category: 'Desert',
            name: 'Papanași cu dulceață de afine',
            weight: '300 g',
            price: '29 RON',
            description:
                'Brânză de vaci, făină, ou, esență vanilie, lămâie, zahăr, dulceață de afine, smântână, portocală.',
            image: null,
            },
            {
            id: 'lava-cake-inghetata',
            category: 'Desert',
            name: 'Lava cake cu înghețată',
            weight: '150 g',
            price: '30 RON',
            description:
                'Cacao, unt, făină, zahăr, ouă, înghețată.',
            image: null,
            },
            {
            id: 'clatite-dulceata-afine',
            category: 'Desert',
            name: 'Clătite cu dulceață de afine',
            weight: '100 g',
            price: '19 RON',
            description: 'Ou, făină, lapte, zahăr, dulceață de afine.',
            image: null,
            },
        ],
    },
];

export const menuDrinks = [
    {
        id: 'racoritoare',
        label: 'Răcoritoare & fresh',
        items: [
            {
            id: 'apa-dorna-330',
            category: 'Răcoritoare',
            name: 'Apă Dorna 330 ml (plată sau carbogazoasă)',
            weight: '330 ml',
            price: '10 RON',
            description: 'Apă Dorna 330 ml, plată sau carbogazoasă.',
            image: null,
        }, {
            id: 'apa-dorna-750',
            category: 'Răcoritoare',
            name: 'Apă Dorna 750 ml (plată sau carbogazoasă)',
            weight: '750 ml',
            price: '19 RON',
            description: 'Apă Dorna 750 ml, plată sau carbogazoasă.',
            image: null,
            },
            {
            id: 'coca-cola-250',
            category: 'Răcoritoare',
            name: 'Coca Cola 250 ml (sugar / zero)',
            weight: '250 ml',
            price: '14 RON',
            description: 'Coca Cola 250 ml, sugar sau zero zahăr.',
            image: null,
            },
            {
            id: 'fanta-250',
            category: 'Răcoritoare',
            name: 'Fanta 250 ml (portocale / struguri)',
            weight: '250 ml',
            price: '14 RON',
            description: 'Fanta 250 ml, de portocale sau struguri.',
            image: null,
            },
            {
            id: 'schweppes-250',
            category: 'Răcoritoare',
            name: 'Schweppes 250 ml',
            weight: '250 ml',
            price: '14 RON',
            description: 'Schweppes 250 ml – bitter lemon, pink tonic sau tonic.',
            image: null,
            },
            {
            id: 'limonada-250',
            category: 'Răcoritoare',
            name: 'Limonadă 250 ml',
            weight: '250 ml',
            price: '15 RON',
            description: 'Suc de lămâie, apă, miere de albine.',
            image: null,
            },
            {
            id: 'cappy-nectar-250',
            category: 'Răcoritoare',
            name: 'Cappy Nectar 250 ml',
            weight: '250 ml',
            price: '14 RON',
            description: 'Nectar Cappy: portocale, piersică, portocale roșii, pere sau vișine.',
            image: null,
            },
            {
            id: 'fresh-portocala-250',
            category: 'Fresh',
            name: 'Fresh portocală',
            weight: '250 ml',
            price: '15 RON',
            description: 'Fresh de portocală proaspăt stors.',
            image: null,
            },
            {
            id: 'fresh-grapefruit-250',
            category: 'Fresh',
            name: 'Fresh grapefruit',
            weight: '250 ml',
            price: '19 RON',
            description: 'Fresh de grapefruit proaspăt stors.',
            image: null,
            },
        ],
        },
        {
        id: 'bere',
        label: 'Bere',
        items: [
            {
            id: 'grimbergen-ambre-330',
            category: 'Bere',
            name: 'Grimbergen Ambre',
            weight: '330 ml',
            price: '18 RON',
            description: 'Bere Grimbergen Ambre 330 ml.',
            image: null,
            },
            // Bere blondă – la sticlă/doză
            {
            id: 'tuborg-green-500',
            category: 'Bere blondă',
            name: 'Tuborg Green',
            weight: '500 ml',
            price: '12 RON',
            description: 'Bere blondă Tuborg Green 500 ml.',
            image: null,
            },
            {
            id: 'tuborg-ice-330',
            category: 'Bere blondă',
            name: 'Tuborg Ice',
            weight: '330 ml',
            price: '10 RON',
            description: 'Bere Tuborg Ice 330 ml.',
            image: null,
            },
            {
            id: 'carlsberg-300',
            category: 'Bere blondă',
            name: 'Carlsberg',
            weight: '300 ml',
            price: '14 RON',
            description: 'Bere Carlsberg 300 ml.',
            image: null,
            },
            {
            id: 'carlsberg-500',
            category: 'Bere blondă',
            name: 'Carlsberg',
            weight: '500 ml',
            price: '15 RON',
            description: 'Bere Carlsberg 500 ml.',
            image: null,
            },
            {
            id: 'bucur-blonda-350',
            category: 'Bere blondă',
            name: 'Bucur blondă',
            weight: '350 ml',
            price: '15 RON',
            description: 'Bere Bucur blondă 350 ml.',
            image: null,
            },
            {
            id: 'holsten-weizen-500',
            category: 'Bere',
            name: 'Holsten Weizen',
            weight: '500 ml',
            price: '18 RON',
            description: 'Bere Holsten Weizen 500 ml.',
            image: null,
            },
            {
            id: 'weihenstephaner-500',
            category: 'Bere',
            name: 'Weihenstephaner',
            weight: '500 ml',
            price: '21 RON',
            description: 'Bere Weihenstephaner 500 ml.',
            image: null,
            },
            // Bere draft
            {
            id: 'tuborg-draft-400',
            category: 'Bere draft',
            name: 'Tuborg draft',
            weight: '400 ml',
            price: '13 RON',
            description: 'Bere draft Tuborg 400 ml.',
            image: null,
            },
            {
            id: 'carlsberg-draft-400',
            category: 'Bere draft',
            name: 'Carlsberg draft',
            weight: '400 ml',
            price: '16 RON',
            description: 'Bere draft Carlsberg 400 ml.',
            image: null,
            },
            {
            id: 'holsten-nefiltrat-400',
            category: 'Bere draft',
            name: 'Holsten Nefiltrat draft',
            weight: '400 ml',
            price: '19 RON',
            description: 'Bere draft Holsten Nefiltrat 400 ml.',
            image: null,
            },
            {
            id: 'tuborg-330',
            category: 'Bere blondă',
            name: 'Tuborg',
            weight: '330 ml',
            price: '10 RON',
            description: 'Bere Tuborg 330 ml.',
            image: null,
            },
        ],
        },
        {
        id: 'cocktailuri',
        label: 'Cocktailuri cu alcool',
        items: [
            {
            id: 'aperol-spritz-240',
            category: 'Cocktail',
            name: 'Aperol Spritz',
            weight: '240 ml',
            price: '35 RON',
            description:
                'Aperol, prosecco, apă carbogazoasă, gheață, felie de portocală.',
            image: null,
            },
            {
            id: 'hugo-230',
            category: 'Cocktail',
            name: 'Hugo',
            weight: '230 ml',
            price: '35 RON',
            description:
                'Prosecco, sirop de soc, apă carbogazoasă, mentă, lime, gheață.',
            image: null,
            },
            {
            id: 'cuba-libre',
            category: 'Cocktail',
            name: 'Cuba Libre',
            weight: null,
            price: '32 RON',
            description: 'Rom, Coca-Cola, gheață, felie de lime.',
            image: null,
            },
            {
            id: 'gin-tonic-300',
            category: 'Cocktail',
            name: 'Gin Tonic',
            weight: '300 ml',
            price: '32 RON',
            description: 'Gin, apă tonică, gheață, felie de lime.',
            image: null,
            },
        ],
        },
        {
        id: 'spirtoase',
        label: 'Digestive & spirtoase',
        items: [
            {
            id: 'jagermeister-50',
            category: 'Digestive',
            name: 'Jägermeister',
            weight: '50 ml',
            price: '14 RON',
            description: 'Digestiv Jägermeister.',
            image: null,
            },
            {
            id: 'tequila-camino-50',
            category: 'Tequila',
            name: 'Tequila Camino',
            weight: '50 ml',
            price: '14 RON',
            description: 'Tequila Camino, 50 ml.',
            image: null,
            },
            {
            id: 'wembley-gin-50',
            category: 'Gin',
            name: 'Wembley Dry Gin',
            weight: '50 ml',
            price: '18 RON',
            description: 'Gin Wembley Dry Gin, 50 ml.',
            image: null,
            },
            {
            id: 'rachiu-gutuie-50',
            category: 'Rachiu',
            name: 'Rachiu Ungheni de gutuie',
            weight: '50 ml',
            price: '24 RON',
            description: 'Rachiu de gutuie Ungheni, 50 ml.',
            image: null,
            },
            {
            id: 'rachiu-pere-50',
            category: 'Rachiu',
            name: 'Rachiu Ungheni de pere',
            weight: '50 ml',
            price: '24 RON',
            description: 'Rachiu de pere Ungheni, 50 ml.',
            image: null,
            },
            {
            id: 'visinata-50',
            category: 'Lichior',
            name: 'Lichior Ungheni de vișină',
            weight: '50 ml',
            price: '24 RON',
            description: 'Vișinată / lichior de vișine Ungheni, 50 ml.',
            image: null,
            },
            {
            id: 'vodka-absolut-50',
            category: 'Vodka',
            name: 'Vodka Absolut',
            weight: '50 ml',
            price: '14 RON',
            description: 'Vodka Absolut, 50 ml.',
            image: null,
            },
            {
            id: 'vodka-finlandia-50',
            category: 'Vodka',
            name: 'Vodka Finlandia',
            weight: '50 ml',
            price: '14 RON',
            description: 'Vodka Finlandia, 50 ml.',
            image: null,
            },
            {
            id: 'brandy-kvint-50',
            category: 'Brandy',
            name: 'Brandy Kvint',
            weight: '50 ml',
            price: '14 RON',
            description: 'Brandy Kvint, 50 ml.',
            image: null,
            },
            {
            id: 'brandy-alexandrion-50',
            category: 'Brandy',
            name: 'Alexandrion 5*',
            weight: '50 ml',
            price: '12 RON',
            description: 'Brandy Alexandrion 5*, 50 ml.',
            image: null,
            },
            {
            id: 'brandy-vechea-romana-50',
            category: 'Brandy',
            name: 'Vechea Română Nero',
            weight: '50 ml',
            price: '14 RON',
            description: 'Brandy Vechea Română Nero, 50 ml.',
            image: null,
            },
            {
            id: 'sheridans-50',
            category: 'Liqueur & Cream',
            name: "Sheridan's Coffee",
            weight: '50 ml',
            price: '18 RON',
            description: "Lichior Sheridan's Coffee, 50 ml.",
            image: null,
            },
        ],
        },
        {
        id: 'vinuri',
        label: 'Vinuri',
        items: [
            // Crama Euforia
            {
            id: 'euforia-tamaioasa-750',
            category: 'Vin',
            name: 'Euforia Tămâioasă Românească alb demisec',
            weight: 'sticlă',
            price: '110 RON',
            description: 'Euforia – Tămâioasă Românească, alb demisec.',
            image: null,
            },
            {
            id: 'euforia-feteasca-alba-750',
            category: 'Vin',
            name: 'Euforia Fetească Albă alb sec',
            weight: 'sticlă',
            price: '120 RON',
            description: 'Euforia – Fetească Albă, alb sec.',
            image: null,
            },
            // Cotnari Naiv
            {
            id: 'cotnari-naiv-tamaioasa-750',
            category: 'Vin',
            name: 'Cotnari Naiv Tămâioasă Românească alb sec',
            weight: 'sticlă',
            price: '120 RON',
            description: 'Cotnari Naiv – Tămâioasă Românească, alb sec.',
            image: null,
            },
            // Cotnari Domenii
            {
            id: 'cotnari-domenii-feteasca-alba-750',
            category: 'Vin',
            name: 'Cotnari Domenii Fetească Albă alb sec',
            weight: 'sticlă',
            price: '72 RON',
            description: 'Cotnari Domenii – Fetească Albă, alb sec.',
            image: null,
            },
            {
            id: 'cotnari-domenii-tamaioasa-750',
            category: 'Vin',
            name: 'Cotnari Domenii Tămâioasă Românească alb demisec',
            weight: 'sticlă',
            price: '72 RON',
            description: 'Cotnari Domenii – Tămâioasă Românească, alb demisec.',
            image: null,
            },
            {
            id: 'cotnari-domenii-busuioaca-750',
            category: 'Vin',
            name: 'Cotnari Domenii Busuioacă de Bohotin roze demisec',
            weight: 'sticlă',
            price: '72 RON',
            description: 'Cotnari Domenii – Busuioacă de Bohotin, roze demisec.',
            image: null,
            },
            // Taraboste
            {
            id: 'taraboste-merlot-cabernet-750',
            category: 'Vin',
            name: 'Taraboste Merlot & Cabernet Sauvignon roșu',
            weight: 'sticlă',
            price: '180 RON',
            description: 'Taraboste – Merlot & Cabernet Sauvignon, roșu.',
            image: null,
            },
            // Portugalia & spumant
            {
            id: 'zaz-spumant-roze-750',
            category: 'Vin spumant',
            name: 'Zaz Spumant Roze',
            weight: 'sticlă',
            price: '65 RON',
            description: 'Zaz Spumant Roze.',
            image: null,
            },
            {
            id: 'zaz-spumant-alb-750',
            category: 'Vin spumant',
            name: 'Zaz Spumant Alb',
            weight: 'sticlă',
            price: '65 RON',
            description: 'Zaz Spumant Alb.',
            image: null,
            },
            {
            id: 'vinho-verde-casal-garcia-750',
            category: 'Vin',
            name: 'Vinho Verde Casal Garcia',
            weight: 'sticlă',
            price: '96 RON',
            description: 'Vin portughez Vinho Verde Casal Garcia.',
            image: null,
            },
            {
            id: 'cotnari-spumant-alb-1l',
            category: 'Vin spumant',
            name: 'Cotnari alb demisec',
            weight: '1 l',
            price: '38 RON',
            description: 'Vin spumant Cotnari alb demisec, 1 l.',
            image: null,
            },
            {
            id: 'cotnari-spumant-rosu-1l',
            category: 'Vin spumant',
            name: 'Cotnari roșu sec',
            weight: '1 l',
            price: '38 RON',
            description: 'Vin spumant Cotnari roșu sec, 1 l.',
            image: null,
            },
            // Vinul casei – la pahar / 1 l
            {
            id: 'vinul-casei-feteasca-neagra-750',
            category: 'Vinul casei',
            name: 'Vinul casei Fetească neagră roșu sec',
            weight: 'sticlă',
            price: '72 RON',
            description: 'Vinul casei – Fetească neagră, roșu sec.',
            image: null,
            },
            {
            id: 'pahar-tamaioasa-150',
            category: 'Pahar vin',
            name: 'Tămâioasă Românească (pahar)',
            weight: '150 ml',
            price: '17 RON',
            description: 'Tămâioasă Românească, alb demisec, pahar 150 ml.',
            image: null,
            },
            {
            id: 'pahar-busuioaca-150',
            category: 'Pahar vin',
            name: 'Busuioacă de Bohotin (pahar)',
            weight: '150 ml',
            price: '17 RON',
            description: 'Busuioacă de Bohotin, roze demisec, pahar 150 ml.',
            image: null,
            },
            {
            id: 'pahar-feteasca-neagra-150',
            category: 'Pahar vin',
            name: 'Fetească neagră (pahar)',
            weight: '150 ml',
            price: '17 RON',
            description: 'Fetească neagră, roșu sec, pahar 150 ml.',
            image: null,
            },
            {
            id: 'pahar-feteasca-alba-150',
            category: 'Pahar vin',
            name: 'Fetească Albă (pahar)',
            weight: '150 ml',
            price: '17 RON',
            description: 'Fetească Albă, alb sec, pahar 150 ml.',
            image: null,
            },
            {
            id: 'cotnari-rosu-demidulce-1l',
            category: 'Vin',
            name: 'Cotnari roșu demidulce',
            weight: '1 l',
            price: '38 RON',
            description: 'Cotnari roșu demidulce, 1 l.',
            image: null,
            },
        ],
    }
];
